addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "0.14.4")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"        % "0.5.5")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.5.0")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph"% "0.8.2")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"          % "1.4.1")
